### ISSUE TITLE
how to bypass CreateToolhelp32Snapshot

### ISSUE THREAD

**Issue by ashyerv** [JakobKlocker/NexonGameSecurity-bypass#1]
CreateToolhelp32Snapshot -> TH32CS_SNAPMODULE
ngs will scan module ngs will check cheat engine dll (VEH)

EnumProcessModulesEx use edit peb to bypass (FAKE DLL)

**Comment by JakobKlocker** [comment]
I'm not sure what exactly you're asking.
If you want to bypass CreateToolhelp32Snapshot hook NtOpenProcess/ZwOpenProcess.
CreateToolhelp32Snapshot uses NtOpenProcess to get a handle to the process, all you have to do is return an error message for the processes you want to hide. Check hooks.cpp line 229.

**Comment by ashyerv** [comment]
thx replay~
do you will make multi client? for this code
